services:
  - type: web
    name: whisper-audio-api
    runtime: python
    envVars:
      - key: WHISPER_MODEL
        value: Systran/faster-whisper-small.en
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn audio_app:app --host 0.0.0.0 --port $PORT
